path_generator:
  ros__parameters:
    #points stored as a flat list of doubles.
    # For each point: [x, y]
    path_points: [0.0, -2.0]  #, 1.0, 1.0, 0.0, 1.0, 0.0, 0.0] #square
    #path_points: [1.0, 0.0] #1.5, 0.5, 1.5, -0.5, 1.0, 0.0] #cocktail glass normal
    #path_points: [1.5, 0.5, 1.5, -0.5, 0.0, 0.0, 1.0, 0.0] #cocktail glass alternate

    #path_points: [-1.2, 0.0] # Error validation

# path_control:
#   ros__parameters:
#     #Controller Gains
#     kp_v: 0.2 #Linear velocity gain
#     kp_w: 1.2 #Angular velocity gain
#     #Tolerance Threshold
#     goal_threshold: 0.05 
#     #Maximum velocities
#     max_v: 0.5 #Max velocity
#     max_w: 1.0 #Max angular velocity

controller:
  ros__parameters:
    goal_threshold: 0.06
    kp_v: 0.20
    kp_w: 0.9
    max_v: 0.28
    max_w: 0.9
    bug_mode: 0
    bug_enabled: true
    bug_hit_dist: 0.2
    bug_leave_tol: 0.08
    bug_leave_margin: 0.08
    bug_max_follow_time: 45.0
    front_d_safety: 0.50
    front_sector: 0.45
    corner_enter_dist: 0.55
    corner_exit_dist: 0.80
    corner_turn_w: 0.70
    corner_linear_v: 0.015
    wall_follow_direction: "fwccw"
